Added support of asynchronous blueprint functions
pragmagic/nimue4 pull request #21
Opened 2017-01-27 10:08 UTC by MednauN

2017-01-31 04:35 UTC, endragor requested changes

2017-01-31 04:35 UTC, endragor commented on modules/core/kismet/blueprintasyncactionbase.nim
> +wclass(UBlueprintAsyncActionBase of UObject, header: "Kismet/BlueprintAsyncActionBase.h", notypedef):
you don't actually need to have `type` declaration and then use `notypedef` in `wclass` macro. `notypedef` is only necessary when you need to forward-declare types.

2017-01-31 04:35 UTC, endragor commented on macros/bpasync.nim
> +macro blueprintAsync*(params: untyped, body: untyped): untyped =
So let's change this to have similar syntax to the [{.blueprint.} pragma](https://github.com/pragmagic/nimue4/wiki/Blueprint-Libraries#blueprint-pragma).

2017-01-31 06:24 UTC, MednauN commented on macros/bpasync.nim
> +macro blueprintAsync*(params: untyped, body: untyped): untyped =
Surprisingly, it's already supported thanks to ``parseMacroOpts`` proc.

2017-02-10 03:45 UTC, endragor approved these changes

2017-02-10 03:48 UTC, merged